name: 'Text to Typing SVG'
description: 'Generate a typing animation SVG for a README'
author: 'Summer'

inputs:
  text:
    description: 'Text to Animate'
    required: true
  
  color:
    description: 'Text Color'
    default: 'white'
  
  font:
    description: 'Font to Render'
    default: 'Arial'
  
  font-size:
    description: 'Font Size'
    default: 20

outputs:
  svg:
    description: 'Generated SVG content'

runs:
  using: 'node16'
  main: 'dist/index.js'