name: Create SVG Typing Animation

on:
  # Allow user to force it to run
  workflow_dispatch:

jobs:
  svg-typing:
    runs-on: ubuntu-latest

    # Steps for Github Action
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Generate Typing SVG
        uses: supersigma453/svg-typing-text@1.0.0
        with:
          text: |
            'Welcome to my Profile!'
            'Super Cool Text',
            'Hai lo;l'
      - name: Update README
        run: |
          git config --local user.email github-actions-${{ github.event.repository.name }}@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git add README.md
          git commit -m "Updated with Typing"
          git push
